user: pi
group: pi
local_home_dir: /Users/robertopozzi
local_ssl_dir: "{{ local_home_dir }}/opt/windfire/ssl"
local_certs_dir: "{{ local_ssl_dir }}/certs/raspberry"
remote_home_dir: /home/pi
remote_ssl_dir: "{{ remote_home_dir }}/opt/windfire/ssl"
remote_keystore_dir: "{{ remote_ssl_dir }}/keystore"
remote_truststore_dir: "{{ remote_ssl_dir }}/truststore"
windfire_ca_root_certificate: "WindfireRootCA.crt"
windfire_server_certificate: "windfire-security.crt"
windfire_server_key: "windfire-security.key"
remote_windfire_security_dir: "{{ remote_home_dir }}/windfire-security"
venv_path: "{{ remote_windfire_security_dir }}/server/windfire-security-server"
python_interpreter: "python3"
install_python_modules_script: installPrereqs.sh
run_server_script: start-auth-server.sh
stop_server_script: stop-auth-server.sh
process: authServer.py